import type { ToolkitItem, WorkflowTemplate } from "./types";

// Realistic seed data drawn from the knowledge/ dossiers and design spec examples.
// This will be replaced by API calls once the backend is live.

export const ITEMS: ToolkitItem[] = [
  {
    id: "a1000000-0000-0000-0000-000000000001",
    slug: "aslov2",
    canonical_name: "AsLOV2",
    item_type: "protein_domain",
    family: "LOV",
    summary:
      "Light-responsive LOV-domain actuator from Avena sativa. Blue-light absorption triggers Jα-helix undocking, enabling steric switching in engineered fusion constructs. One of the most widely reused optogenetic actuator domains.",
    status: "curated",
    maturity_stage: "preclinical",
    first_publication_year: 2002,
    primary_input_modality: "light",
    primary_output_modality: "conformational_change",
    mechanisms: ["conformational_uncaging"],
    techniques: [],
    target_processes: ["localization", "signaling", "transcription"],
    synonyms: ["Avena sativa LOV2", "LOV2"],
    validation_rollup: {
      has_cell_free_validation: true,
      has_bacterial_validation: true,
      has_mammalian_cell_validation: true,
      has_mouse_in_vivo_validation: true,
      has_human_clinical_validation: false,
      has_therapeutic_use: false,
      has_independent_replication: true,
    },
    replication_summary: {
      score_version: "v1",
      primary_paper_count: 48,
      independent_primary_paper_count: 31,
      distinct_last_author_clusters: 22,
      distinct_institutions: 18,
      distinct_biological_contexts: 7,
      years_since_first_report: 23,
      downstream_application_count: 35,
      orphan_tool_flag: false,
      practicality_penalties: ["moderate dark-state leak in some fusions"],
      evidence_strength_score: 0.91,
      replication_score: 0.88,
      practicality_score: 0.76,
      translatability_score: 0.42,
    },
    citations: [
      {
        id: "c001",
        source_document_id: "d001",
        citation_role: "foundational",
        importance_rank: 1,
        why_this_matters:
          "First characterization of the LOV2-Jα photoswitching mechanism enabling rational fusion design.",
        document: {
          id: "d001",
          source_type: "primary_paper",
          title:
            "The LOV2 domain of phototropin: a reversible photochromic switch",
          doi: "10.1021/bi026978l",
          pmid: "12553882",
          publication_year: 2003,
          journal_or_source: "Biochemistry",
          is_retracted: false,
        },
      },
      {
        id: "c002",
        source_document_id: "d002",
        citation_role: "best_review",
        importance_rank: 2,
        why_this_matters:
          "Comprehensive review of LOV-domain engineering covering design rules and known failure modes.",
        document: {
          id: "d002",
          source_type: "review",
          title:
            "Designing Photoswitchable Peptides Using the AsLOV2 Domain",
          doi: "10.1021/acs.chemrev.8b00723",
          pmid: "30550275",
          publication_year: 2019,
          journal_or_source: "Chemical Reviews",
          is_retracted: false,
        },
      },
      {
        id: "c003",
        source_document_id: "d003",
        citation_role: "independent_validation",
        importance_rank: 3,
        why_this_matters:
          "Demonstrates LOV2-based nuclear export system in mammalian cells with quantified kinetics.",
        document: {
          id: "d003",
          source_type: "primary_paper",
          title: "A light-inducible organelle-targeting system for dynamically activating and inactivating signaling in budding yeast",
          doi: "10.1091/mbc.e18-01-0029",
          pmid: "nil",
          publication_year: 2018,
          journal_or_source: "Molecular Biology of the Cell",
          is_retracted: false,
        },
      },
    ],
    validations: [
      {
        id: "v001",
        item_id: "a1000000-0000-0000-0000-000000000001",
        observation_type: "mechanistic_demo",
        biological_system_level: "cell_free",
        species: null,
        cell_type: null,
        delivery_mode: "purified protein",
        success_outcome: "success",
        assay_description: "In vitro spectroscopic characterization of LOV2 photocycle",
        construct_name: "AsLOV2-Jα wild type",
        independent_lab_cluster_id: "lab_harper",
        metrics: [
          { metric_name: "off_kinetics_minutes", value_num: 1.4, unit: "min", qualifier: "t½" },
        ],
      },
      {
        id: "v002",
        item_id: "a1000000-0000-0000-0000-000000000001",
        observation_type: "application_demo",
        biological_system_level: "mammalian_cell_line",
        species: "human",
        cell_type: "HEK293T",
        delivery_mode: "transient transfection",
        success_outcome: "success",
        assay_description: "Light-induced nuclear export with fluorescence imaging",
        construct_name: "LEXY (LOV2-NES)",
        independent_lab_cluster_id: "lab_bhatt",
        metrics: [
          { metric_name: "fold_induction", value_num: 8.5, unit: "fold", qualifier: null },
          { metric_name: "dark_state_leak", value_num: 0.12, unit: "fraction", qualifier: null },
        ],
      },
      {
        id: "v003",
        item_id: "a1000000-0000-0000-0000-000000000001",
        observation_type: "application_demo",
        biological_system_level: "bacteria",
        species: "E. coli",
        cell_type: null,
        delivery_mode: "plasmid",
        success_outcome: "success",
        assay_description: "LOV2-caged degron controlling protein stability",
        construct_name: "LOV2-ssrA degron",
        independent_lab_cluster_id: "lab_bhatt",
        metrics: [
          { metric_name: "fold_induction", value_num: 15.0, unit: "fold", qualifier: null },
        ],
      },
      {
        id: "v004",
        item_id: "a1000000-0000-0000-0000-000000000001",
        observation_type: "application_demo",
        biological_system_level: "mouse",
        species: "Mus musculus",
        cell_type: null,
        delivery_mode: "AAV injection",
        success_outcome: "mixed",
        assay_description: "In vivo optogenetic control of gene expression in mouse brain with LOV-based transcription factor",
        construct_name: "LOV2-VP16 TF",
        independent_lab_cluster_id: "lab_bhatt_2",
        metrics: [
          { metric_name: "fold_induction", value_num: 3.2, unit: "fold", qualifier: "brain tissue" },
        ],
      },
    ],
  },
  {
    id: "a1000000-0000-0000-0000-000000000002",
    slug: "cry2-cib1",
    canonical_name: "CRY2/CIB1",
    item_type: "multi_component_switch",
    family: "cryptochrome",
    summary:
      "Blue-light-inducible heterodimerization pair from Arabidopsis thaliana. CRY2 photoexcitation drives rapid association with CIB1, enabling membrane recruitment, transcriptional activation, and condensate formation.",
    status: "curated",
    maturity_stage: "research",
    first_publication_year: 2010,
    primary_input_modality: "light",
    primary_output_modality: "signaling",
    mechanisms: ["heterodimerization"],
    techniques: [],
    target_processes: ["signaling", "localization", "transcription"],
    synonyms: ["CRY2-CIB1", "cryptochrome 2 / CIB1"],
    validation_rollup: {
      has_cell_free_validation: false,
      has_bacterial_validation: false,
      has_mammalian_cell_validation: true,
      has_mouse_in_vivo_validation: false,
      has_human_clinical_validation: false,
      has_therapeutic_use: false,
      has_independent_replication: true,
    },
    replication_summary: {
      score_version: "v1",
      primary_paper_count: 34,
      independent_primary_paper_count: 20,
      distinct_last_author_clusters: 14,
      distinct_institutions: 12,
      distinct_biological_contexts: 4,
      years_since_first_report: 15,
      downstream_application_count: 22,
      orphan_tool_flag: false,
      practicality_penalties: [
        "CRY2 homo-oligomerization can compete with CIB1 binding",
        "slower off-kinetics limit temporal precision",
      ],
      evidence_strength_score: 0.82,
      replication_score: 0.79,
      practicality_score: 0.68,
      translatability_score: 0.28,
    },
    citations: [
      {
        id: "c010",
        source_document_id: "d010",
        citation_role: "foundational",
        importance_rank: 1,
        why_this_matters:
          "First demonstration of CRY2-CIB1 as a genetically encoded light-switchable interaction pair.",
        document: {
          id: "d010",
          source_type: "primary_paper",
          title: "A light-triggered protein secretion system",
          doi: "10.1038/ncb2103",
          pmid: "20418870",
          publication_year: 2010,
          journal_or_source: "Nature Cell Biology",
          is_retracted: false,
        },
      },
    ],
    validations: [
      {
        id: "v010",
        item_id: "a1000000-0000-0000-0000-000000000002",
        observation_type: "application_demo",
        biological_system_level: "mammalian_cell_line",
        species: "human",
        cell_type: "HeLa",
        delivery_mode: "transient transfection",
        success_outcome: "success",
        assay_description: "Membrane recruitment of CIB1-fused effector via CRY2-CIBN at plasma membrane",
        construct_name: "CRY2-mCherry / CIBN-CAAX",
        independent_lab_cluster_id: "lab_bhatt_2",
        metrics: [
          { metric_name: "on_kinetics_minutes", value_num: 0.1, unit: "min", qualifier: null },
          { metric_name: "off_kinetics_minutes", value_num: 5.5, unit: "min", qualifier: null },
        ],
      },
    ],
  },
  {
    id: "a1000000-0000-0000-0000-000000000003",
    slug: "el222",
    canonical_name: "EL222",
    item_type: "protein_domain",
    family: "LOV",
    summary:
      "Bacterial LOV-HTH transcription factor from Erythrobacter litoralis. Blue light triggers dimerization and DNA binding, enabling compact light-inducible gene expression systems.",
    status: "curated",
    maturity_stage: "research",
    first_publication_year: 2012,
    primary_input_modality: "light",
    primary_output_modality: "transcription",
    mechanisms: ["dna_binding", "oligomerization"],
    techniques: [],
    target_processes: ["transcription"],
    synonyms: ["EL222 LOV-HTH"],
    validation_rollup: {
      has_cell_free_validation: true,
      has_bacterial_validation: true,
      has_mammalian_cell_validation: true,
      has_mouse_in_vivo_validation: false,
      has_human_clinical_validation: false,
      has_therapeutic_use: false,
      has_independent_replication: true,
    },
    replication_summary: {
      score_version: "v1",
      primary_paper_count: 18,
      independent_primary_paper_count: 11,
      distinct_last_author_clusters: 9,
      distinct_institutions: 8,
      distinct_biological_contexts: 4,
      years_since_first_report: 13,
      downstream_application_count: 12,
      orphan_tool_flag: false,
      practicality_penalties: ["requires custom promoter element (C120)"],
      evidence_strength_score: 0.74,
      replication_score: 0.72,
      practicality_score: 0.71,
      translatability_score: 0.31,
    },
    citations: [
      {
        id: "c020",
        source_document_id: "d020",
        citation_role: "foundational",
        importance_rank: 1,
        why_this_matters:
          "First characterization of EL222 as a light-switchable transcription factor for synthetic biology.",
        document: {
          id: "d020",
          source_type: "primary_paper",
          title: "An engineered optogenetic switch for spatiotemporal control of gene expression, cell differentiation, and tissue morphogenesis",
          doi: "10.1021/sb500305v",
          pmid: "25524168",
          publication_year: 2014,
          journal_or_source: "ACS Synthetic Biology",
          is_retracted: false,
        },
      },
    ],
    validations: [
      {
        id: "v020",
        item_id: "a1000000-0000-0000-0000-000000000003",
        observation_type: "application_demo",
        biological_system_level: "mammalian_cell_line",
        species: "human",
        cell_type: "HEK293T",
        delivery_mode: "transient transfection",
        success_outcome: "success",
        assay_description: "Blue-light-driven reporter expression via EL222-C120 system",
        construct_name: "VP-EL222 + C120-mCherry",
        independent_lab_cluster_id: "lab_bhatt_2",
        metrics: [
          { metric_name: "fold_induction", value_num: 200, unit: "fold", qualifier: null },
          { metric_name: "dark_state_leak", value_num: 0.02, unit: "fraction", qualifier: null },
        ],
      },
      {
        id: "v021",
        item_id: "a1000000-0000-0000-0000-000000000003",
        observation_type: "mechanistic_demo",
        biological_system_level: "bacteria",
        species: "E. coli",
        cell_type: null,
        delivery_mode: "plasmid",
        success_outcome: "success",
        assay_description: "Bacterial gene expression control with EL222-C120 promoter",
        construct_name: "EL222-C120-GFP",
        independent_lab_cluster_id: "lab_tabor",
        metrics: [
          { metric_name: "fold_induction", value_num: 460, unit: "fold", qualifier: null },
        ],
      },
    ],
  },
  {
    id: "a1000000-0000-0000-0000-000000000004",
    slug: "phocl",
    canonical_name: "PhoCl",
    item_type: "protein_domain",
    family: "fluorescent_protein",
    summary:
      "Photocleavable fluorescent protein. Violet light triggers irreversible backbone cleavage, releasing a caged peptide or domain. Useful for one-shot activation of effectors.",
    status: "normalized",
    maturity_stage: "research",
    first_publication_year: 2017,
    primary_input_modality: "light",
    primary_output_modality: "conformational_change",
    mechanisms: ["photocleavage"],
    techniques: [],
    target_processes: ["signaling", "localization"],
    synonyms: ["PhoCl1", "PhoCl2"],
    validation_rollup: {
      has_cell_free_validation: true,
      has_bacterial_validation: false,
      has_mammalian_cell_validation: true,
      has_mouse_in_vivo_validation: false,
      has_human_clinical_validation: false,
      has_therapeutic_use: false,
      has_independent_replication: true,
    },
    replication_summary: {
      score_version: "v1",
      primary_paper_count: 8,
      independent_primary_paper_count: 4,
      distinct_last_author_clusters: 3,
      distinct_institutions: 3,
      distinct_biological_contexts: 3,
      years_since_first_report: 8,
      downstream_application_count: 5,
      orphan_tool_flag: false,
      practicality_penalties: [
        "irreversible — cannot be reset",
        "violet light required — limited tissue penetration",
        "slow cleavage kinetics",
      ],
      evidence_strength_score: 0.52,
      replication_score: 0.45,
      practicality_score: 0.48,
      translatability_score: 0.15,
    },
    citations: [],
    validations: [
      {
        id: "v030",
        item_id: "a1000000-0000-0000-0000-000000000004",
        observation_type: "mechanistic_demo",
        biological_system_level: "cell_free",
        species: null,
        cell_type: null,
        delivery_mode: "purified protein",
        success_outcome: "success",
        assay_description: "In vitro photocleavage kinetics of PhoCl under 400 nm illumination",
        construct_name: "PhoCl1",
        independent_lab_cluster_id: "lab_bhatt_2",
        metrics: [],
      },
      {
        id: "v031",
        item_id: "a1000000-0000-0000-0000-000000000004",
        observation_type: "application_demo",
        biological_system_level: "mammalian_cell_line",
        species: "human",
        cell_type: "HeLa",
        delivery_mode: "transient transfection",
        success_outcome: "success",
        assay_description: "Light-triggered release of caged Cre recombinase via PhoCl cleavage",
        construct_name: "PhoCl-Cre",
        independent_lab_cluster_id: "lab_bhatt_2",
        metrics: [],
      },
    ],
  },
  {
    id: "a1000000-0000-0000-0000-000000000005",
    slug: "ribosome-display",
    canonical_name: "Ribosome Display",
    item_type: "engineering_method",
    family: "display_selection",
    summary:
      "Cell-free selection platform that links mRNA to its translated protein via stalled ribosome complexes. Enables directed evolution of binding proteins without cellular transformation bottlenecks.",
    status: "curated",
    maturity_stage: "deployed",
    first_publication_year: 1997,
    primary_input_modality: "sequence",
    primary_output_modality: "selection",
    mechanisms: [],
    techniques: ["selection_enrichment"],
    target_processes: ["selection"],
    synonyms: ["ribosome display selection"],
    validation_rollup: {
      has_cell_free_validation: true,
      has_bacterial_validation: false,
      has_mammalian_cell_validation: false,
      has_mouse_in_vivo_validation: false,
      has_human_clinical_validation: false,
      has_therapeutic_use: true,
      has_independent_replication: true,
    },
    replication_summary: {
      score_version: "v1",
      primary_paper_count: 120,
      independent_primary_paper_count: 80,
      distinct_last_author_clusters: 45,
      distinct_institutions: 35,
      distinct_biological_contexts: 2,
      years_since_first_report: 28,
      downstream_application_count: 60,
      orphan_tool_flag: false,
      practicality_penalties: ["RNase sensitivity", "requires high-quality mRNA preps"],
      evidence_strength_score: 0.95,
      replication_score: 0.94,
      practicality_score: 0.82,
      translatability_score: 0.88,
    },
    citations: [],
    validations: [],
  },
  {
    id: "a1000000-0000-0000-0000-000000000006",
    slug: "rfdiffusion",
    canonical_name: "RFdiffusion",
    item_type: "computation_method",
    family: "protein_design",
    summary:
      "Generative deep-learning model for de novo protein structure design. Uses denoising diffusion on protein backbones conditioned on functional motifs, symmetry, and binding targets.",
    status: "curated",
    maturity_stage: "research",
    first_publication_year: 2023,
    primary_input_modality: "structure",
    primary_output_modality: "structure",
    mechanisms: [],
    techniques: ["computational_design"],
    target_processes: ["signaling", "selection"],
    synonyms: ["RF diffusion", "RoseTTAFold Diffusion"],
    validation_rollup: {
      has_cell_free_validation: true,
      has_bacterial_validation: true,
      has_mammalian_cell_validation: false,
      has_mouse_in_vivo_validation: false,
      has_human_clinical_validation: false,
      has_therapeutic_use: false,
      has_independent_replication: true,
    },
    replication_summary: {
      score_version: "v1",
      primary_paper_count: 22,
      independent_primary_paper_count: 14,
      distinct_last_author_clusters: 10,
      distinct_institutions: 9,
      distinct_biological_contexts: 3,
      years_since_first_report: 2,
      downstream_application_count: 15,
      orphan_tool_flag: false,
      practicality_penalties: ["requires GPU compute", "experimental validation still needed for each design"],
      evidence_strength_score: 0.78,
      replication_score: 0.65,
      practicality_score: 0.62,
      translatability_score: 0.22,
    },
    citations: [],
    validations: [],
  },
  {
    id: "a1000000-0000-0000-0000-000000000007",
    slug: "amplicon-ngs",
    canonical_name: "Amplicon NGS",
    item_type: "assay_method",
    family: "sequencing",
    summary:
      "Targeted next-generation sequencing of PCR-amplified regions. Standard readout for pooled editing experiments, library selections, and allele frequency measurements.",
    status: "curated",
    maturity_stage: "deployed",
    first_publication_year: 2005,
    primary_input_modality: "sequence",
    primary_output_modality: "assay_readout",
    mechanisms: [],
    techniques: ["sequence_verification"],
    target_processes: ["selection", "editing"],
    synonyms: ["amplicon sequencing", "targeted NGS"],
    validation_rollup: {
      has_cell_free_validation: false,
      has_bacterial_validation: true,
      has_mammalian_cell_validation: true,
      has_mouse_in_vivo_validation: true,
      has_human_clinical_validation: true,
      has_therapeutic_use: true,
      has_independent_replication: true,
    },
    replication_summary: {
      score_version: "v1",
      primary_paper_count: 500,
      independent_primary_paper_count: 400,
      distinct_last_author_clusters: 200,
      distinct_institutions: 150,
      distinct_biological_contexts: 9,
      years_since_first_report: 20,
      downstream_application_count: 300,
      orphan_tool_flag: false,
      practicality_penalties: ["primer bias possible", "short read length limits some applications"],
      evidence_strength_score: 0.99,
      replication_score: 0.99,
      practicality_score: 0.95,
      translatability_score: 0.97,
    },
    citations: [],
    validations: [],
  },
  {
    id: "a1000000-0000-0000-0000-000000000008",
    slug: "proteinmpnn",
    canonical_name: "ProteinMPNN",
    item_type: "computation_method",
    family: "protein_design",
    summary:
      "Message-passing neural network for protein sequence design given a fixed backbone structure. Rapid inverse folding enables high-throughput sequence optimization for designed scaffolds.",
    status: "curated",
    maturity_stage: "research",
    first_publication_year: 2022,
    primary_input_modality: "structure",
    primary_output_modality: "sequence",
    mechanisms: [],
    techniques: ["computational_design"],
    target_processes: ["selection"],
    synonyms: ["ProteinMPNN", "MPNN"],
    validation_rollup: {
      has_cell_free_validation: true,
      has_bacterial_validation: true,
      has_mammalian_cell_validation: false,
      has_mouse_in_vivo_validation: false,
      has_human_clinical_validation: false,
      has_therapeutic_use: false,
      has_independent_replication: true,
    },
    replication_summary: {
      score_version: "v1",
      primary_paper_count: 30,
      independent_primary_paper_count: 22,
      distinct_last_author_clusters: 15,
      distinct_institutions: 12,
      distinct_biological_contexts: 3,
      years_since_first_report: 3,
      downstream_application_count: 20,
      orphan_tool_flag: false,
      practicality_penalties: [],
      evidence_strength_score: 0.81,
      replication_score: 0.74,
      practicality_score: 0.80,
      translatability_score: 0.25,
    },
    citations: [],
    validations: [],
  },
  {
    id: "a1000000-0000-0000-0000-000000000009",
    slug: "pace-pance",
    canonical_name: "PACE / PANCE",
    item_type: "engineering_method",
    family: "directed_evolution",
    summary:
      "Phage-assisted continuous / non-continuous evolution platforms. Use M13 bacteriophage lifecycle to link protein function to phage propagation, enabling rapid directed evolution without manual rounds.",
    status: "curated",
    maturity_stage: "research",
    first_publication_year: 2011,
    primary_input_modality: "sequence",
    primary_output_modality: "selection",
    mechanisms: [],
    techniques: ["directed_evolution", "selection_enrichment"],
    target_processes: ["selection"],
    synonyms: ["PACE", "PANCE", "phage-assisted evolution"],
    validation_rollup: {
      has_cell_free_validation: false,
      has_bacterial_validation: true,
      has_mammalian_cell_validation: false,
      has_mouse_in_vivo_validation: false,
      has_human_clinical_validation: false,
      has_therapeutic_use: false,
      has_independent_replication: true,
    },
    replication_summary: {
      score_version: "v1",
      primary_paper_count: 28,
      independent_primary_paper_count: 12,
      distinct_last_author_clusters: 8,
      distinct_institutions: 7,
      distinct_biological_contexts: 1,
      years_since_first_report: 14,
      downstream_application_count: 10,
      orphan_tool_flag: false,
      practicality_penalties: [
        "complex setup requiring custom phage plumbing",
        "limited to E. coli hosts",
        "high failure rate for novel selection circuits",
      ],
      evidence_strength_score: 0.72,
      replication_score: 0.58,
      practicality_score: 0.42,
      translatability_score: 0.18,
    },
    citations: [],
    validations: [],
  },
  {
    id: "a1000000-0000-0000-0000-000000000010",
    slug: "mrna-display",
    canonical_name: "mRNA Display",
    item_type: "engineering_method",
    family: "display_selection",
    summary:
      "Cell-free selection platform where mRNA is covalently linked to its translated protein via puromycin. Supports very large library sizes (>10^13) and non-natural amino acid incorporation.",
    status: "curated",
    maturity_stage: "deployed",
    first_publication_year: 1997,
    primary_input_modality: "sequence",
    primary_output_modality: "selection",
    mechanisms: [],
    techniques: ["selection_enrichment"],
    target_processes: ["selection"],
    synonyms: ["mRNA display", "puromycin display"],
    validation_rollup: {
      has_cell_free_validation: true,
      has_bacterial_validation: false,
      has_mammalian_cell_validation: false,
      has_mouse_in_vivo_validation: false,
      has_human_clinical_validation: false,
      has_therapeutic_use: true,
      has_independent_replication: true,
    },
    replication_summary: {
      score_version: "v1",
      primary_paper_count: 90,
      independent_primary_paper_count: 60,
      distinct_last_author_clusters: 35,
      distinct_institutions: 28,
      distinct_biological_contexts: 2,
      years_since_first_report: 28,
      downstream_application_count: 45,
      orphan_tool_flag: false,
      practicality_penalties: ["puromycin ligation efficiency variable", "RNase sensitivity"],
      evidence_strength_score: 0.92,
      replication_score: 0.90,
      practicality_score: 0.78,
      translatability_score: 0.82,
    },
    citations: [],
    validations: [],
  },
];

export const WORKFLOWS: WorkflowTemplate[] = [
  {
    id: "w001",
    slug: "fast-no-cloning-screen",
    name: "Fast No-Cloning Screen",
    workflow_family: "fast_screen",
    objective: "Quick yes/no functional test of a known sequence or small design set without cloning",
    throughput_class: "low",
    recommended_for: "Known designs, small candidate sets, cell-free-compatible assays",
    steps: [
      {
        id: "ws001",
        step_name: "Design candidate",
        step_type: "design",
        duration_typical_hours: 2,
        hands_on_hours: 2,
        direct_cost_usd_typical: 0,
        parallelizable: false,
        failure_probability: 0.05,
        input_artifact: null,
        output_artifact: "sequence",
      },
      {
        id: "ws002",
        step_name: "Order gene fragment",
        step_type: "dna_acquisition",
        duration_typical_hours: 48,
        hands_on_hours: 0.5,
        direct_cost_usd_typical: 120,
        parallelizable: true,
        failure_probability: 0.02,
        input_artifact: "sequence",
        output_artifact: "linear DNA",
      },
      {
        id: "ws003",
        step_name: "Cell-free expression + assay",
        step_type: "assay",
        duration_typical_hours: 6,
        hands_on_hours: 3,
        direct_cost_usd_typical: 80,
        parallelizable: true,
        failure_probability: 0.15,
        input_artifact: "linear DNA",
        output_artifact: "assay readout",
      },
      {
        id: "ws004",
        step_name: "Analyze results",
        step_type: "analysis",
        duration_typical_hours: 2,
        hands_on_hours: 2,
        direct_cost_usd_typical: 0,
        parallelizable: false,
        failure_probability: 0.02,
        input_artifact: "assay readout",
        output_artifact: "decision",
      },
    ],
  },
  {
    id: "w002",
    slug: "standard-construct-loop",
    name: "Standard Construct Engineering Loop",
    workflow_family: "standard_construct",
    objective: "Full build-test cycle for engineered constructs requiring cloning and host-cell validation",
    throughput_class: "single",
    recommended_for: "Constructs where host context, expression level, and fusion geometry matter",
    steps: [
      {
        id: "ws010",
        step_name: "Design construct",
        step_type: "design",
        duration_typical_hours: 4,
        hands_on_hours: 4,
        direct_cost_usd_typical: 0,
        parallelizable: false,
        failure_probability: 0.05,
        input_artifact: null,
        output_artifact: "sequence",
      },
      {
        id: "ws011",
        step_name: "Order gene fragment",
        step_type: "dna_acquisition",
        duration_typical_hours: 120,
        hands_on_hours: 0.5,
        direct_cost_usd_typical: 180,
        parallelizable: true,
        failure_probability: 0.03,
        input_artifact: "sequence",
        output_artifact: "linear DNA",
      },
      {
        id: "ws012",
        step_name: "Assemble / clone",
        step_type: "assembly",
        duration_typical_hours: 8,
        hands_on_hours: 3,
        direct_cost_usd_typical: 30,
        parallelizable: false,
        failure_probability: 0.10,
        input_artifact: "linear DNA",
        output_artifact: "cloned plasmid",
      },
      {
        id: "ws013",
        step_name: "Sequence verify",
        step_type: "sequence_verification",
        duration_typical_hours: 24,
        hands_on_hours: 1,
        direct_cost_usd_typical: 15,
        parallelizable: true,
        failure_probability: 0.15,
        input_artifact: "cloned plasmid",
        output_artifact: "verified plasmid",
      },
      {
        id: "ws014",
        step_name: "Transfect / transform",
        step_type: "transfection",
        duration_typical_hours: 4,
        hands_on_hours: 2,
        direct_cost_usd_typical: 40,
        parallelizable: false,
        failure_probability: 0.10,
        input_artifact: "verified plasmid",
        output_artifact: "expressing cells",
      },
      {
        id: "ws015",
        step_name: "Functional assay",
        step_type: "assay",
        duration_typical_hours: 24,
        hands_on_hours: 4,
        direct_cost_usd_typical: 60,
        parallelizable: false,
        failure_probability: 0.20,
        input_artifact: "expressing cells",
        output_artifact: "assay readout",
      },
      {
        id: "ws016",
        step_name: "Analyze and iterate",
        step_type: "analysis",
        duration_typical_hours: 4,
        hands_on_hours: 4,
        direct_cost_usd_typical: 0,
        parallelizable: false,
        failure_probability: 0.02,
        input_artifact: "assay readout",
        output_artifact: "decision",
      },
    ],
  },
  {
    id: "w003",
    slug: "library-selection-loop",
    name: "Library Selection Loop",
    workflow_family: "library_selection",
    objective: "Directed evolution or combinatorial selection from a large molecular library",
    throughput_class: "library_scale",
    recommended_for: "Binding affinity maturation, novel binder discovery, enzyme engineering",
    steps: [
      {
        id: "ws020",
        step_name: "Design library",
        step_type: "design",
        duration_typical_hours: 8,
        hands_on_hours: 8,
        direct_cost_usd_typical: 0,
        parallelizable: false,
        failure_probability: 0.10,
        input_artifact: null,
        output_artifact: "library design",
      },
      {
        id: "ws021",
        step_name: "Build library",
        step_type: "assembly",
        duration_typical_hours: 72,
        hands_on_hours: 12,
        direct_cost_usd_typical: 2000,
        parallelizable: false,
        failure_probability: 0.15,
        input_artifact: "library design",
        output_artifact: "DNA library",
      },
      {
        id: "ws022",
        step_name: "Selection rounds",
        step_type: "selection_round",
        duration_typical_hours: 48,
        hands_on_hours: 16,
        direct_cost_usd_typical: 500,
        parallelizable: false,
        failure_probability: 0.20,
        input_artifact: "DNA library",
        output_artifact: "enriched pool",
      },
      {
        id: "ws023",
        step_name: "Amplicon NGS readout",
        step_type: "assay",
        duration_typical_hours: 72,
        hands_on_hours: 4,
        direct_cost_usd_typical: 400,
        parallelizable: true,
        failure_probability: 0.05,
        input_artifact: "enriched pool",
        output_artifact: "sequence data",
      },
      {
        id: "ws024",
        step_name: "Pick winners and validate",
        step_type: "analysis",
        duration_typical_hours: 16,
        hands_on_hours: 8,
        direct_cost_usd_typical: 200,
        parallelizable: false,
        failure_probability: 0.10,
        input_artifact: "sequence data",
        output_artifact: "validated candidates",
      },
    ],
  },
];

export function getItemBySlug(slug: string): ToolkitItem | undefined {
  return ITEMS.find((i) => i.slug === slug);
}

export function getItemsByType(itemType: string): ToolkitItem[] {
  return ITEMS.filter((i) => i.item_type === itemType);
}

export function getItemsByMechanism(mechanism: string): ToolkitItem[] {
  return ITEMS.filter((i) => i.mechanisms.includes(mechanism));
}

export function getItemsByTechnique(technique: string): ToolkitItem[] {
  return ITEMS.filter((i) => i.techniques.includes(technique));
}

export function getItemsByFamily(family: string): ToolkitItem[] {
  return ITEMS.filter((i) => i.family === family);
}

export function getAllFamilies(): string[] {
  const families = new Set(ITEMS.map((i) => i.family).filter(Boolean) as string[]);
  return Array.from(families).sort();
}

export function getAllMechanisms(): string[] {
  const mechanisms = new Set(ITEMS.flatMap((i) => i.mechanisms));
  return Array.from(mechanisms).sort();
}

export function getAllTechniques(): string[] {
  const techniques = new Set(ITEMS.flatMap((i) => i.techniques));
  return Array.from(techniques).sort();
}
